services:
  webhook-handler:
    build:
      context: .
      args:
        ARTIFACTORY_USER: "__token__"
        ARTIFACTORY_PWD: ${GROUP_TOKEN}
    image: ${DOCKER_IMAGE}
    container_name: webhook-handler
    ports:
      - "46720:9095"
    restart: always
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
    entrypoint:
      - /bin/bash
      - -c
      - python app/webhook_handler/serve.py --env=${SCOPE}
    env_file:
      - path: .env

networks:
  default:
    external: true
    name: ${CONTAINER_NETWORK}
